### ISSUE TITLE
The v2.1 NuGet package doesn't work

### ISSUE THREAD

**Issue by cpmcgrath** [damirkusar/AspNetCore.Totp#3]
Hi,
The 2.1 package has a dependency on AspNetCore.Totp.Interface which doesn't exist - 
https://www.nuget.org/packages/AspNetCore.Totp/
https://www.nuget.org/packages/AspNetCore.Totp.Interface/

**Comment by damirkusar** [comment]
Hi @cpmcgrath, can you try again with 2.2.. i was able to install it without any problems, it seems that dotnet pack has a problem with these packages.. if it is not working.. i will create a 2.3 and upload the interface seperately.

**Comment by damirkusar** [comment]
Ok.. it seemed it was in my cache :) uploaded version 2.3 with the interface separately. Now it should work.
