### ISSUE TITLE
Generator returns invalid code

### ISSUE THREAD

**Issue by XFox111** [damirkusar/AspNetCore.Totp#7]
I've tried to use this library with other TOTP generators (like Microsoft Authenticator or [this online authenticator] (https://rootprojects.org/authenticator/)) and codes generated with the library and the other ones are different

![image](https://user-images.githubusercontent.com/28831743/119260803-1d611400-bbdd-11eb-9515-81a9a0c3492d.png)

This happens because when hashing, it doesn't decode a secret which is Base32 encoded string:

```csharp
// AspNetCore.Totp.Helper.TotpHasher.cs:9:14
internal static int Hash(string secret, long iterationNumber, int digits = 6)
{
        var key = Encoding.UTF8.GetBytes(secret);
        //var key = Base32Encoder.Encode(secret);
        return Hash(key, iterationNumber, digits);
}
```

So, all you need is to use decoder you've wrote in `Base32.cs`:

```csharp
// AspNetCore.Totp.Helper.TotpHasher.cs:9
internal static int Hash(string secret, long iterationNumber, int digits = 6)
{
        var key = Base32.Decode(secret);
        return Hash(key, iterationNumber, digits);
}
```

If you want, I can prepare a PR for this issue

**Comment by damirkusar** [comment]
Thanks for your comment. Yes Please.

**Comment by XFox111** [comment]
Can you assign me to the issue?
