### ISSUE TITLE
return File(qrCode.QrCodeImageBytes, "image/png"); not working

### ISSUE THREAD

**Issue by HassanZeitoun** [damirkusar/AspNetCore.Totp#8]
return File(qrCode.QrCodeImageBytes, "image/png"); 
always giving me that 
'TotpSetup' does not contain a definition for 'QrCodeImageBytes' and no accessible extension method 'QrCodeImageBytes' accepting a first argument of type 'TotpSetup' could be found (are you missing a using directive or an assembly reference?)

everything else works fine

**Comment by simon-curtis** [comment]
Which version are you using? 2.3.0 (current nuget version) or 3.0.0 (current repo version)

**Comment by sujit1779** [comment]
I think you should use below line for version 2.3.0
 return File(qrCode.QrCodeImage, "image/png");
